import type { PatternType, MonsterConfig } from '../types'

export const MONSTERS: Record<PatternType, MonsterConfig> = {
  urgency: {
    pattern_type: 'urgency',
    monster_name: 'Ticking Bomb',
    color: '#ff4444',
    glowColor: '#ff6666',
    depth_range: [50, 200],
  },
  scarcity: {
    pattern_type: 'scarcity',
    monster_name: 'Scarcity Skeleton',
    color: '#d4aa00',
    glowColor: '#ffcc00',
    depth_range: [100, 300],
  },
  misdirection: {
    pattern_type: 'misdirection',
    monster_name: 'Mimic Chest',
    color: '#8b4513',
    glowColor: '#cd853f',
    depth_range: [150, 400],
  },
  forced_action: {
    pattern_type: 'forced_action',
    monster_name: 'Wall Trap',
    color: '#666666',
    glowColor: '#999999',
    depth_range: [200, 500],
  },
  social_proof: {
    pattern_type: 'social_proof',
    monster_name: 'Ghost Horde',
    color: '#88aaff',
    glowColor: '#aaccff',
    depth_range: [150, 450],
  },
  sneaking: {
    pattern_type: 'sneaking',
    monster_name: 'Floor Trap',
    color: '#556b2f',
    glowColor: '#7cfc00',
    depth_range: [250, 550],
  },
  obstruction: {
    pattern_type: 'obstruction',
    monster_name: 'Locked Door',
    color: '#8b0000',
    glowColor: '#ff2222',
    depth_range: [300, 600],
  },
  confirmshaming: {
    pattern_type: 'confirmshaming',
    monster_name: 'Guilt Ghost',
    color: '#9944cc',
    glowColor: '#cc66ff',
    depth_range: [350, 650],
  },
  disguised_ads: {
    pattern_type: 'disguised_ads',
    monster_name: 'Shape Shifter',
    color: '#228b22',
    glowColor: '#44ff44',
    depth_range: [400, 700],
  },
  nagging: {
    pattern_type: 'nagging',
    monster_name: 'Swarm Bats',
    color: '#333333',
    glowColor: '#ff4444',
    depth_range: [200, 500],
  },
  trick_questions: {
    pattern_type: 'trick_questions',
    monster_name: 'Riddle Sphinx',
    color: '#daa520',
    glowColor: '#ffd700',
    depth_range: [500, 800],
  },
  hidden_costs: {
    pattern_type: 'hidden_costs',
    monster_name: 'Price Phantom',
    color: '#4a0080',
    glowColor: '#8800ff',
    depth_range: [600, 900],
  },
  bait_and_switch: {
    pattern_type: 'bait_and_switch',
    monster_name: 'ANGLERFISH',
    color: '#003322',
    glowColor: '#00ff88',
    depth_range: [1000, 1200],
  },
}
